#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=12gb
#PBS -l walltime=06:00:00
#PBS -q short
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/simulation/expression/salmon/indexIMGT.out

salmon=/home/vitor/Salmon-0.8.2_linux_x86_64/bin/salmon

indexDIR=./index
fasta=../../../imgt_index/gencode.v25.PRI.IMGT.transcripts.fa

cd $PBS_O_WORKDIR

mkdir -p $indexDIR

$salmon index -t $fasta -i $indexDIR --type quasi -k 31 
