#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=1gb
#PBS -l walltime=02:00:00
#PBS -q short 
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/eqtl_mapping/genomemapping/3-conditional_analysis/log/

cd $PBS_O_WORKDIR

qtltools=/home/vitor/qtltools/bin/QTLtools

datadir=/home/vitor/hlaexpression/geuvadis_reanalysis/data
SAMPLES=$datadir/genotypes/samples.eur
VCF=$datadir/genotypes/eur_maf05.vcf.gz
COV=$datadir/pca_genotypes/covariates_genos.txt
BED=../1-phenotypes/phenotypes_eur_$PC.bed.gz
THR=../2-permutations/results/permutations_$PC.thresholds.txt
OUT=./conditional_$PC

$qtltools cis --vcf $VCF --bed $BED --cov $COV --mapping $THR\
    --include-samples $SAMPLES --normal --chunk $CHUNK 60 --out ${OUT}_$CHUNK.txt
