#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-999
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/eqtl_mapping/quasimapping/hla_personalized/caveman/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log
mkdir -p ./results

caveman=/home/vitor/CaVEMaN
BED=./phenotypes_corrected.bed
VCF=/home/vitor/hlaexpression/geuvadis_reanalysis/data/genotypes/eur_maf05.vcf.gz

$caveman --bed $BED --vcf $VCF --genes 6 --job-number $PBS_ARRAYID \
    --out results/results$PBS_ARRAYID --verbose
