#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l mem=36gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-50
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/simulation/PEreads_75bp/expression/1-map_to_genome/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log
mkdir -p ./mappings/mhc_fqs
mkdir -p ./quantifications
mkdir -p ./quantifications_uniq

SAMPLE=$(printf "sample_%02d" $PBS_ARRAYID)

./map_and_quantify.sh $SAMPLE 
