#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-7
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/qtls/star/imgt/rtc/gwas/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log

QTLtools=/home/vitor/QTLtools/QTLtools_1.1_Ubuntu16.04_x86_64

SAMPLES=../../../../genotypes/samples.eur
VCF=../../../../genotypes/eur_maf05.vcf.gz
COV=../../../../pca_genotypes/covariates_genos.txt
BED=../../1-phenotypes/phenotypes_eur_60.bed.gz
HOTSPOTS=../hotspots_hg38_fixed_distances.bed
CATALOG=./gwas_catalog_filtered.txt
COND=../../3-conditional_analysis/conditional_60_all.txt.gz

REGION=`awk "NR==$PBS_ARRAYID" ./hla_regions.txt`

OUT=./rtc_results_$REGION.txt

$QTLtools rtc --vcf $VCF --bed $BED --include-samples $SAMPLES\
    --region $REGION --D-prime-threshold 0.5\
    --cov $COV --hotspot $HOTSPOTS --gwas-cis $CATALOG $COND --normal\
    --conditional --out $OUT
