#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1001-1839
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/qtls/star/supplemented/caveman/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

caveman=/home/vitor/CaVEMaN
BED=./phenotypes_corrected.bed
VCF=/home/vitor/hlaexpression/geuvadis_reanalysis/qtls/genotypes/eur_maf05.vcf.gz

$caveman --bed $BED --vcf $VCF --genes 6 --job-number $PBS_ARRAYID \
    --out results/results$PBS_ARRAYID --verbose
