#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/qtls/qtls_star/imgt/trans/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log

QTLtools=/home/vitor/QTLtools/QTLtools_1.1_Ubuntu16.04_x86_64

SAMPLES=../../../genotypes/samples.eur
VCF=../../../genotypes/eur_maf05.vcf.gz
COV=../../../pca_genotypes/covariates_genos.txt
BED=../1-phenotypes/phenotypes_eur_60.bed.gz
OUT=./trans_nulldist

$QTLtools trans --vcf $VCF --cov $COV --bed $BED --sample 1000 --normal --out $OUT
