#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -l walltime=36:00:00
#PBS -q long
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/qtls/star/imgt/trans/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

QTLtools=/home/vitor/QTLtools/QTLtools_1.1_Ubuntu16.04_x86_64

SAMPLES=../../../genotypes/samples.eur
VCF=../../../genotypes/eur_maf05.vcf.gz
COV=../../../pca_genotypes/covariates_genos.txt
BED=../1-phenotypes/phenotypes_eur_60.bed.gz
NULL=./trans_nulldist.best.txt.gz
OUT=./trans_adjust

$QTLtools trans --vcf $VCF --cov $COV --bed $BED --adjust $NULL --normal\
    --threshold 0.05 --out $OUT
