#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=6gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-358
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/expression/5-pseudoalignment/hla_personalized/log/$PBS_JOBIB.log

cd $PBS_O_WORKDIR

mkdir -p ./quantifications_2

SAMPLE=`awk "NR==$PBS_ARRAYID" ../../../data/sample_info/samples_phase3_ena_eur.txt`

./quantify_round2.sh $SAMPLE
