#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l mem=12gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-358
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/expression/4-quasimapping/hla_personalized/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log
mkdir -p ./quantifications

SAMPLE=`awk "FNR==$PBS_ARRAYID" ../../../data/sample_info/samples_phase3_ena_eur.txt`

./quantify.sh $SAMPLE
