#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=12gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/simulation/PEreads_75bp/isoforms/data/log/$PBS_JOBID.log

SAMPLE=sample_01

cd $PBS_O_WORKDIR

mkdir -p ./log
mkdir -p ./fastq
mkdir -p ./fasta

Rscript polyester.R 1 

for i in {1..2}
do
    cat ./fasta/sample_01_$i.fasta |\
	awk -v mate=$i 'BEGIN {RS = ">" ; FS = "\n"} NR > 1 {
	    print\
	    "@"gensub(/;/, " ", 1, gensub(/\//, "_", 1, $1))"/"mate"\n"\
	    $2"\n"\
	    "+\n"\
	    gensub(/./, ">", "g", $2)\
	}' | gzip -c > ./fastq/${SAMPLE}_$i.fastq.gz
done

rm -r ./fasta
