#!/bin/bash

#PBS -l nodes=1:ppn=6
#PBS -l mem=8gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-358
#PBS -j oe
#PBS -o /home/vitor/hlaexpression/geuvadis_reanalysis/expression/star/log/$PBS_NAMEID.log

cd $PBS_O_WORKDIR

mkdir -p ./log
mkdir -p ./mappings_1
mkdir -p ./quantifications_1

SAMPLE=`awk "NR==$PBS_ARRAYID" ../../data/sample_info/samples_phase3_ena_eur.txt`

./map_and_quantify_round1.sh $SAMPLE
