---
title: "HLA project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r pkgs}
library(tidyverse)
library(knitr)
```

```{r}
expression_df <- read_tsv("./results_geneva_hospital.tsv")

gene_df <- expression_df %>%
    group_by(subject, gene) %>%
    summarize(tpm = sum(tpm)) %>%
    group_by(gene) %>%
    filter(mean(tpm) > 10) %>%
    ungroup()

lineage_df <- expression_df %>%
    mutate(lineage = sub("^([^:]+).+$", "\\1", allele))
```


## Gene-level expression

*HLA genes with mean expression > 10 TPM*

```{r fig.width=12, fig.height=6, dpi=200}
ggplot(gene_df, aes(gene, tpm)) +
    geom_jitter(aes(color = subject), size = 2.5, width = 0.25) +
    geom_boxplot(outlier.shape = NA, fill = NA, color = "grey55") +
    theme_bw() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_text(size = 16),
          axis.text.x = element_text(size = 14, angle = 90, hjust = 1, vjust = 0.5),
          axis.text.y = element_text(size = 14),
          legend.text = element_text(size = 14),
          legend.title = element_text(size = 16),
          legend.position = "top") +
    ggthemes::scale_color_colorblind() +
    labs(y = "TPM")
```

## HLA lineages

```{r, fig.width=10, fig.height=12, dpi=200}
lineage_df %>%
    filter(gene %in% paste0("HLA-", c("A", "B", "C", "DPB1", "DQA1", "DQB1", "DRB1"))) %>%
    ggplot(aes(x = reorder(lineage, tpm, FUN = median, na.rm = TRUE), y = tpm)) +
    geom_boxplot(outlier.shape = NA, fill = NA, color = "grey55", alpha = .1) +
    geom_jitter(aes(color = subject), size = 3, width = 0.25) +
    ggthemes::scale_color_colorblind() +
    scale_x_discrete(labels = function(x) gsub("\\*", "*\n", x)) +
    facet_wrap(~gene, scales = "free", ncol = 1, strip.position = "left") +
    labs(x = " ", y = "TPM") +
    theme_bw() +
    theme(axis.title = element_text(size = 16),
	  axis.text = element_text(size = 12),
	  strip.text = element_text(face = "bold", size = 16),
  	  legend.text = element_text(size = 14),
	  legend.title = element_text(size = 16),
	  legend.position = "top") +
    guides(color = guide_legend(override.aes = list(alpha = 1, size = 2)))
```
